[metadata]
name = starlingx-zuul-jobs
summary = A set of Ansible playbooks used by StarlingX for CI
description-file =
    README.rst
author = StarlingX Team
author-email = starlingx-discuss@lists.starlingx.io
home-page = https://starlingx.io/
classifier =
    Intended Audience :: Information Technology
    Intended Audience :: System Administrators
    License :: OSI Approved :: Apache Software License
    Operating System :: POSIX :: Linux
    Programming Language :: Python

[build_sphinx]
source-dir = doc/source
build-dir = doc/build
all_files = 1
warning-is-error = 1
